### ISSUE TITLE
Expose number of aex9 token holders in token information endpoint

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1257]
Hey,
currently to get the number of aex9 token holders we need to paginate through all of the `/v2/aex9/:contract_id/balances` pages which on the frontend is very far from ideal. It's easy to imagine a token airdropped to multiple accounts that will generate a long balances list resulting in killing the device that tries to go through that list (not to mention the time and bandwidth needed to transfer all of that information). 

Could we expose the number of token holders in `/v2/aex9/:contract_id` to save the hustle and optimize the performance on the client-side? :)

**Comment by jyeshe** [comment]
Aex9 compliance to standard to be classified by #1410

**Comment by michele-franchi** [comment]
@jyeshe I see a PR for the fix was merged but I noticed a difference between the count `holders` and the balances endpoint.
Example:
- https://mainnet.aeternity.io/mdw/v2/aex9/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt returns `"holders": 38`
- https://mainnet.aeternity.io/mdw/v2/aex9/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt/balances?limit=100 returns 40 entries

**Comment by janmichek** [comment]
Hi, this does not seem to be resolved yet.

The example above still shows 63 entries and 62 in `holders` field.

Here is another example

![image](https://github.com/aeternity/ae_mdw/assets/15363559/b136c4fc-0bf4-4466-8126-7ec40b321822)

**Comment by janmichek** [comment]
@jyeshe ping

**Comment by jyeshe** [comment]
> @jyeshe ping

Need to hold...

**Comment by janmichek** [comment]
Hello, do we have some updates on this?

**Comment by janmichek** [comment]
There is a difference between length for balance endpoint for V2 and V3. Currently we are using v3. Should I downgrade to v2 so the length and count are the same?

https://mainnet.aeternity.io/mdw/v3/aex9/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt/balances?by=amount&limit=100

https://mainnet.aeternity.io/mdw/v2/aex9/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt/balances?limit=100

**Comment by vatanasov** [comment]
The problem exists in both versions (v2/v3), when they are sorted by amount (basically it's showing balances that equal 0, when it should not).

I would advice to stay on v3 and we will work on fixing the issue when sorting by amount.

**Comment by janmichek** [comment]
> The problem exists in both versions (v2/v3), when they are sorted by amount (basically it's showing balances that equal 0, when it should not).
> 
> I would advice to stay on v3 and we will work on fixing the issue when sorting by amount.

Ok, great. Thanks for your suggestion

**Comment by janmichek** [comment]
Looks implemented .] Thanks

**Comment by janmichek** [comment]
You can close this one
